# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: github-ci-resc-webappdeploymentbucket-gvlaizbldku5

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT, https://stackoverflow.com/a/78230041/554246
      contents: read
    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload artifact to s3
      run: aws s3 cp golang-aws-deployment-test s3://${{ env.S3_BUCKET }}/

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: Dev
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
  #       role-session-name: GitHub-Action-Role
  #       aws-region: ${{ env.AWS_REGION }}
  #   - run: |
  #       echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
  #       commit_hash=`git rev-parse HEAD`
  #       aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=cenan/golang-aws-deployment-test,commitId=$commit_hash --ignore-application-stop-failures
